### ISSUE TITLE
Request to be part of the working group

### ISSUE THREAD

**Issue by pmmalinov01** [ossf/wg-best-practices-oss-developers#13]
I am not able to find a process of how to join the WG. Could you please point me in that direction?

**Comment by xcorail** [comment]
👋🏾 @pmmalinov01 
Please send me your email address and I will add you to the meeting invite

**Comment by dlorenc** [comment]
Could the meeting invite be published so anyone can attend?

**Comment by xcorail** [comment]
Done, the meeting invite is now public in the OSSF calendar
