### ISSUE TITLE
Potentially misleading repository name

### ISSUE THREAD

**Issue by Voultapher** [ossf/wg-best-practices-oss-developers#2]
Taking a look at https://github.com/ossf/tac#technical-initiatives the Technical Initiatives table, reading the name of this project, I first thought it was 'working group best practices operating systems developers', and only realized what it really was about once I opened the repo and started reading the readme. Maybe it's too late to rename this project/repo, just thought I'd let you know the name can be misleading.

**Comment by david-a-wheeler** [comment]
Project/repos *can* be renamed, you just don't want to do it often. In this case, changing "os" to "oss" should do the trick.

I think renaming should be done now, before too many external URLs use the "wrong" one. But that's up to the lead.

**Comment by xcorail** [comment]
Changed, thanks for the feedback @Voultapher
